LANGUAGES = {'afrikaans': 'af',
             'albanian': 'sq',
             'amharic': 'am',
             'arabic': 'ar',
             'armenian': 'hy',
             'azerbaijani': 'az',
             'basque': 'eu',
             'belarusian': 'be',
             'bengali': 'bn',
             'bosnian': 'bs',
             'bulgarian': 'bg',
             'catalan': 'ca',
             'cebuano': 'ceb',
             'chichewa': 'ny',
             'chinese (simplified)': 'zh-cn',
             'chinese (traditional)': 'zh-tw',
             'corsican': 'co',
             'croatian': 'hr',
             'czech': 'cs',
             'danish': 'da',
             'dutch': 'nl',
             'english': 'en',
             'esperanto': 'eo',
             'estonian': 'et',
             'filipino': 'tl',
             'finnish': 'fi',
             'french': 'fr',
             'frisian': 'fy',
             'galician': 'gl',
             'georgian': 'ka',
             'german': 'de',
             'greek': 'el',
             'gujarati': 'gu',
             'haitian creole': 'ht',
             'hausa': 'ha',
             'hawaiian': 'haw',
             'hebrew': 'he',
             'hindi': 'hi',
             'hmong': 'hmn',
             'hungarian': 'hu',
             'icelandic': 'is',
             'igbo': 'ig',
             'indonesian': 'id',
             'irish': 'ga',
             'italian': 'it',
             'japanese': 'ja',
             'javanese': 'jw',
             'kannada': 'kn',
             'kazakh': 'kk',
             'khmer': 'km',
             'korean': 'ko',
             'kurdish (kurmanji)': 'ku',
             'kyrgyz': 'ky',
             'lao': 'lo',
             'latin': 'la',
             'latvian': 'lv',
             'lithuanian': 'lt',
             'luxembourgish': 'lb',
             'macedonian': 'mk',
             'malagasy': 'mg',
             'malay': 'ms',
             'malayalam': 'ml',
             'maltese': 'mt',
             'maori': 'mi',
             'marathi': 'mr',
             'mongolian': 'mn',
             'myanmar (burmese)': 'my',
             'nepali': 'ne',
             'norwegian': 'no',
             'odia': 'or',
             'pashto': 'ps',
             'persian': 'fa',
             'polish': 'pl',
             'portuguese': 'pt',
             'punjabi': 'pa',
             'romanian': 'ro',
             'russian': 'ru',
             'samoan': 'sm',
             'scots gaelic': 'gd',
             'serbian': 'sr',
             'sesotho': 'st',
             'shona': 'sn',
             'sindhi': 'sd',
             'sinhala': 'si',
             'slovak': 'sk',
             'slovenian': 'sl',
             'somali': 'so',
             'spanish': 'es',
             'sundanese': 'su',
             'swahili': 'sw',
             'swedish': 'sv',
             'tajik': 'tg',
             'tamil': 'ta',
             'telugu': 'te',
             'thai': 'th',
             'turkish': 'tr',
             'ukrainian': 'uk',
             'urdu': 'ur',
             'uyghur': 'ug',
             'uzbek': 'uz',
             'vietnamese': 'vi',
             'welsh': 'cy',
             'xhosa': 'xh',
             'yiddish': 'yi',
             'yoruba': 'yo',
             'zulu': 'zu'
             }

LISTENING_TXT = "Please give me something to translate..."
RECOGNIZING_TXT = "I am analyzing your sentence ....."
REPEAT_TXT = "please, say again....."
REQUESTED_TRANSLATION_TXT = 'You said: '
WHICH_LANGUAGE_TXT = 'Give me the language in which you want to convert: ' \
                     'for example: French , Spanish, German or any other'
LANGUAGE_NOT_FOUND_TXT = "I cannot find the language in which you are trying to convert, " \
                         "please say again or give another language"

PROMPT_TEXTS = {
    'listening': LISTENING_TXT,
    'recognizing': RECOGNIZING_TXT,
    'repeat': REPEAT_TXT,
    'requested_translation': REQUESTED_TRANSLATION_TXT,
    'which_language': WHICH_LANGUAGE_TXT,
    'language_not_found': LANGUAGE_NOT_FOUND_TXT
}

VOCALS_PATH = 'vocals'
